development:
  adapter: postgresql
  encoding: unicode
  database: quiz_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: quiz_test
  pool: 5
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: quiz_production
  pool: 5
  username: postgres
  password:
